import z from 'zod'
import { NumberSchema } from '../types/number-type'

export const TotalSchema = z.object({
  baseCalculoIcms: NumberSchema.default(0),
  baseCalculoIcmsSt: NumberSchema.default(0),
  baseCalculoIrrf: NumberSchema.default(0),
  baseCalculoMono: NumberSchema.default(0),
  baseCalculoMonoRetencao: NumberSchema.default(0),
  baseCalculoMonoRetido: NumberSchema.default(0),
  baseCalculoRetencao: NumberSchema.default(0),
  valorAproximadoTributos: NumberSchema.default(0),
  valorCofins: NumberSchema.default(0),
  valorCofinsRetido: NumberSchema.default(0),
  valorCsllRetido: NumberSchema.default(0),
  valorDesconto: NumberSchema.default(0),
  valorFcp: NumberSchema.default(0),
  valorFcpSt: NumberSchema.default(0),
  valorFcpStRetido: NumberSchema.default(0),
  valorFrete: NumberSchema.default(0),
  valorIcms: NumberSchema.default(0),
  valorIcmsDesonerado: NumberSchema.default(0),
  valorIcmsEstadoDestino: NumberSchema.default(0),
  valorIcmsEstadoRemetente: NumberSchema.default(0),
  valorIcmsMono: NumberSchema.default(0),
  valorIcmsMonoRetencao: NumberSchema.default(0),
  valorIcmsMonoRetido: NumberSchema.default(0),
  valorIcmsSt: NumberSchema.default(0),
  valorIi: NumberSchema.default(0),
  valorIpi: NumberSchema.default(0),
  valorIpiDevolvido: NumberSchema.default(0),
  valorIrrfRetido: NumberSchema.default(0),
  valorNFCe: NumberSchema.default(0),
  valorOutros: NumberSchema.default(0),
  valorPis: NumberSchema.default(0),
  valorPisRetido: NumberSchema.default(0),
  valorPrevidenciaRetido: NumberSchema.default(0),
  valorProdutosServicos: NumberSchema.default(0),
  valorSeguro: NumberSchema.default(0),
})

export type Total = z.infer<typeof TotalSchema>
